spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/wanglichaoya/SpringCloudConfig-20191016/
          searchPaths: src
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/